app:
    resource: "@AppBundle/Controller/"
    type:     annotation

links_api:
    type:   rest
    resource: AppBundle\Controller\LinkController
    defaults:
        _format: json

categories_api:
    type:   rest
    resource: AppBundle\Controller\CategoryController
    defaults:
        _format: json